### Authorization by token, part 1. Retrieve and save token.
POST https://examples.http-client.intellij.net/body-echo
Content-Type: application/json

{
  "token": "my-secret-token"
}

> {% client.global.set("auth_token", response.body.token); %}

### Authorization by token, part 2. Use token to authorize.
GET https://api.hubstaff.com/v2/organizations
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImRlZmF1bHQifQ.eyJqdGkiOiJRMEdCa3FLSkxRPT0iLCJpc3MiOiJodHRwczovL2FjY291bnQuaHVic3RhZmYuY29tIiwiZXhwIjoxNzIwMzAxODIxLCJpYXQiOjE3MjAwNDI2MjEsInNjb3BlIjoiaHVic3RhZmY6d3JpdGUgaHVic3RhZmY6cmVhZCIsImF1ZCI6InN3YWdnZXJVSSIsInN1YiI6IlBqS0ZxUjJYcG1kbTJ5aXhUNWlfWHBTWEtyS2EzbEdnMDN5UExmeEJ3dzYxLTR4bTE4T2NEN1ZkNzU4TWpxc1phX3FNTWgwTDZydjQ0dlRFc2R0ZjVBPT0ifQ.ShKsuaVwNmpoS2gaixTaae2JxIPgeshk-FgmeTCKu4TKSe4rRYOah6HQJovVCkcz1TtYCvIww4uRNRUqxWs7KwOTrSW3jR4U9YAe7lKIE5iq-ZjIw9R1r4J67ZsUAykmo8jG6mOsbJ6p1KTy8BQk9CKBsMyCijx1Z8OPySLiqCqmX7sk4B8Lsccrz6B0OkCCzRKrkILgIMxZEq4KjOzM213n67_GmD-1lFJTwI7WTopc7OI-NDNiOw-6Ak8dwKqFJ0Xn5StEUo5GM6MglD9Mt5yeFiTCcInQqS5Pu1rqL4R8KBVobZAl1jGpDMmNKMGo4nwvjor2G1kXYv8EmiGx7w

###
GET https://api.hubstaff.com/v2/users/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImRlZmF1bHQifQ.eyJqdGkiOiJRMEdCa3FLSkxRPT0iLCJpc3MiOiJodHRwczovL2FjY291bnQuaHVic3RhZmYuY29tIiwiZXhwIjoxNzIwMzAxODIxLCJpYXQiOjE3MjAwNDI2MjEsInNjb3BlIjoiaHVic3RhZmY6d3JpdGUgaHVic3RhZmY6cmVhZCIsImF1ZCI6InN3YWdnZXJVSSIsInN1YiI6IlBqS0ZxUjJYcG1kbTJ5aXhUNWlfWHBTWEtyS2EzbEdnMDN5UExmeEJ3dzYxLTR4bTE4T2NEN1ZkNzU4TWpxc1phX3FNTWgwTDZydjQ0dlRFc2R0ZjVBPT0ifQ.ShKsuaVwNmpoS2gaixTaae2JxIPgeshk-FgmeTCKu4TKSe4rRYOah6HQJovVCkcz1TtYCvIww4uRNRUqxWs7KwOTrSW3jR4U9YAe7lKIE5iq-ZjIw9R1r4J67ZsUAykmo8jG6mOsbJ6p1KTy8BQk9CKBsMyCijx1Z8OPySLiqCqmX7sk4B8Lsccrz6B0OkCCzRKrkILgIMxZEq4KjOzM213n67_GmD-1lFJTwI7WTopc7OI-NDNiOw-6Ak8dwKqFJ0Xn5StEUo5GM6MglD9Mt5yeFiTCcInQqS5Pu1rqL4R8KBVobZAl1jGpDMmNKMGo4nwvjor2G1kXYv8EmiGx7w

###
GET https://api.hubstaff.com/v2/organizations/585030/projects?status=active
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImRlZmF1bHQifQ.eyJqdGkiOiJRMEdCa3FLSkxRPT0iLCJpc3MiOiJodHRwczovL2FjY291bnQuaHVic3RhZmYuY29tIiwiZXhwIjoxNzIwMzAxODIxLCJpYXQiOjE3MjAwNDI2MjEsInNjb3BlIjoiaHVic3RhZmY6d3JpdGUgaHVic3RhZmY6cmVhZCIsImF1ZCI6InN3YWdnZXJVSSIsInN1YiI6IlBqS0ZxUjJYcG1kbTJ5aXhUNWlfWHBTWEtyS2EzbEdnMDN5UExmeEJ3dzYxLTR4bTE4T2NEN1ZkNzU4TWpxc1phX3FNTWgwTDZydjQ0dlRFc2R0ZjVBPT0ifQ.ShKsuaVwNmpoS2gaixTaae2JxIPgeshk-FgmeTCKu4TKSe4rRYOah6HQJovVCkcz1TtYCvIww4uRNRUqxWs7KwOTrSW3jR4U9YAe7lKIE5iq-ZjIw9R1r4J67ZsUAykmo8jG6mOsbJ6p1KTy8BQk9CKBsMyCijx1Z8OPySLiqCqmX7sk4B8Lsccrz6B0OkCCzRKrkILgIMxZEq4KjOzM213n67_GmD-1lFJTwI7WTopc7OI-NDNiOw-6Ak8dwKqFJ0Xn5StEUo5GM6MglD9Mt5yeFiTCcInQqS5Pu1rqL4R8KBVobZAl1jGpDMmNKMGo4nwvjor2G1kXYv8EmiGx7w

###
POST https://api.hubstaff.com/v2/users/2700884/time_entries
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImRlZmF1bHQifQ.eyJqdGkiOiJRMEdCa3FLSkxRPT0iLCJpc3MiOiJodHRwczovL2FjY291bnQuaHVic3RhZmYuY29tIiwiZXhwIjoxNzIwMzAxODIxLCJpYXQiOjE3MjAwNDI2MjEsInNjb3BlIjoiaHVic3RhZmY6d3JpdGUgaHVic3RhZmY6cmVhZCIsImF1ZCI6InN3YWdnZXJVSSIsInN1YiI6IlBqS0ZxUjJYcG1kbTJ5aXhUNWlfWHBTWEtyS2EzbEdnMDN5UExmeEJ3dzYxLTR4bTE4T2NEN1ZkNzU4TWpxc1phX3FNTWgwTDZydjQ0dlRFc2R0ZjVBPT0ifQ.ShKsuaVwNmpoS2gaixTaae2JxIPgeshk-FgmeTCKu4TKSe4rRYOah6HQJovVCkcz1TtYCvIww4uRNRUqxWs7KwOTrSW3jR4U9YAe7lKIE5iq-ZjIw9R1r4J67ZsUAykmo8jG6mOsbJ6p1KTy8BQk9CKBsMyCijx1Z8OPySLiqCqmX7sk4B8Lsccrz6B0OkCCzRKrkILgIMxZEq4KjOzM213n67_GmD-1lFJTwI7WTopc7OI-NDNiOw-6Ak8dwKqFJ0Xn5StEUo5GM6MglD9Mt5yeFiTCcInQqS5Pu1rqL4R8KBVobZAl1jGpDMmNKMGo4nwvjor2G1kXYv8EmiGx7w
Content-Type: application/json

{
"note": "tests",
"project_id": "3059362",
"start_time": "2024-07-03T22:20:00.000Z",
"tracked": 100
}